#!/usr/bin/python3

import os
import sys
import time
from subprocess import getoutput as terminal
import string

DRIVER_DIR = '/sys/devices/system/cpu/cpufreq'
GOVERNORS = terminal('cat /sys/devices/system/cpu/cpufreq/policy0/scaling_available_governors').strip().split(' ')
POLICIES = terminal('ls ' + DRIVER_DIR + ' | grep policy').strip().split('\n')

FREQUENCIES = None
if 'scaling_available_frequencies' in terminal('ls /sys/devices/system/cpu/cpufreq/policy0/'):
    FREQUENCIES = terminal('cat /sys/devices/system/cpu/cpufreq/policy0/scaling_available_frequencies').strip().split(' ')
elif 'cpuinfo_max_freq' in terminal('ls /sys/devices/system/cpu/cpufreq/policy0/') and 'cpuinfo_min_freq' in terminal('ls /sys/devices/system/cpu/cpufreq/policy0/'):
    FREQUENCIES = [terminal(f'cat {DRIVER_DIR}/policy0/cpuinfo_min_freq').strip(), terminal(f'cat {DRIVER_DIR}/policy0/cpuinfo_max_freq').strip()]

def setGovernor(governor, cpu):
    if governor not in GOVERNORS:
        return False

    if cpu is True:
        print('Setting governor for all processors to ' + governor)

        for policy in POLICIES:
            os.system(f'echo {governor} > {DRIVER_DIR}/{policy}/scaling_governor')

        return True
    else:
        policy = f'policy{cpu}'

        if policy in POLICIES:
            print('Setting governor for processor ' + str(cpu) + ' to ' + governor)
            os.system(f'echo {governor} > {DRIVER_DIR}/{policy}/scaling_governor')
            return True
        return False

def getCurrentGovernors():
    governors = {}
    for policy in POLICIES:
        governors[policy] = terminal(f'cat {DRIVER_DIR}/{policy}/scaling_governor').strip()

    return governors

def getCurrentScalingFrequencies():
    frequencies = {}

    for policy in POLICIES:
        frequencies[policy] = {'min' : terminal(f'cat {DRIVER_DIR}/{policy}/scaling_min_freq'), 'max' : terminal(f'cat {DRIVER_DIR}/{policy}/scaling_max_freq')}

    return frequencies

def setMinimumScalingFrequency(frequency, cpu):
    if FREQUENCIES is None:
        return False
    
    if cpu is True:
        if frequency not in FREQUENCIES:
            return False

        print('Setting for all processors minimum frequency to ' + str(round(int(frequency) / 1000000, 1)) + ' GHz')
        for policy in POLICIES:
            os.system(f'echo {frequency} > {DRIVER_DIR}/{policy}/scaling_min_freq')

        return True

    else:
        policy = f'policy{cpu}'
        if frequency not in FREQUENCIES:
            return False

        if policy in POLICIES:
            print('Setting for processor ' + str(cpu) + ' minimum frequency to ' + str(round(int(frequency) / 1000000, 1)) + ' GHz')

            os.system(f'echo {frequency} > {DRIVER_DIR}/{policy}/scaling_min_freq')
            return True
        return False

def setMaximumScalingFrequency(frequency, cpu):
    if FREQUENCIES is None:
        return False
        
    if frequency not in FREQUENCIES:
        return False

    if cpu is True:

        print('Setting for all processors maximum frequency to ' + str(round(int(frequency) / 1000000, 1)) + ' GHz')
        for policy in POLICIES:
            os.system(f'echo {frequency} > {DRIVER_DIR}/{policy}/scaling_max_freq')

        return True
    else:
        policy = f'policy{cpu}'

        if policy in POLICIES:
            print('Setting for processor ' + str(cpu) + ' maximum frequency to ' + str(round(int(frequency) / 1000000, 1)) + ' GHz')

            os.system(f'echo {frequency} > {DRIVER_DIR}/{policy}/scaling_max_freq')
            return True
        return False
    
def makeListStructure(stat):
    for index, line in enumerate(stat):
        splitted = line.split(' ')

        for element in splitted:
            if element == '' or element == ' ':
                splitted.remove(element)

        stat[index] = list(int(element) for element in splitted)
    return stat

usageContexts = {
    0 : 'user',
    1 : 'nice',
    2 : 'system',
    3 : 'idle',
    4 : 'iowait',
    5 : 'interrupt',
    6 : 'soft-interrupt'
}

def getParameterUsage(beforeStat, afterStat):
    usage = {}
    beforeSum = sum(beforeStat)
    afterSum = sum(afterStat)

    beforeIdle = beforeStat[3]
    afterIdle = afterStat[3]

    total = afterSum - beforeSum
    totalUsagePercent = (total - (afterIdle - beforeIdle)) * 100 / total
    usage['total'] = round(totalUsagePercent, 2)

    for index, label in usageContexts.items():
        usage[label] = round(
            100 - (total - (afterStat[index] - beforeStat[index])) * 100 / total, 2
        )

    return usage

def cpuUsage():
    beforeStat = terminal('grep cpu -i /proc/stat | awk \'{ $1="" ; print }\'').strip().split('\n')
    time.sleep(0.25)
    afterStat = terminal('grep cpu -i /proc/stat | awk \'{ $1="" ; print }\'').strip().split('\n')

    beforeStat = makeListStructure(beforeStat)
    afterStat = makeListStructure(afterStat)

    usages = []
    for i in range(len(beforeStat)):
        usages.append(getParameterUsage(beforeStat[i], afterStat[i]))

    return usages

def cpuFrequency():
    frequencies = terminal('grep "cpu MHZ" -i /proc/cpuinfo | awk -F \':\' \'{ print $2 }\'').strip().split('\n')
    frequencies = list(round(float(freq.replace(',', '.')), 2) for freq in frequencies)

    average = round(sum(frequencies) / len(frequencies), 2)
    return average, frequencies

def threadDistribution():
    return terminal('grep "core id" -i /proc/cpuinfo | awk -F \':\' \'{ print $2 }\'').strip().split('\n')

def cpuCache():
    baseDir = '/sys/devices/system/cpu'
    cpuDirs = terminal('ls /sys/devices/system/cpu | grep -i cpu').split('\n')

    if 'cpufreq' in cpuDirs:
        cpuDirs.remove('cpufreq')

    if 'cpuidle' in cpuDirs:
        cpuDirs.remove('cpuidle')

    cpuCache = {}
    for cpu in cpuDirs:
        cpuCache[cpu] = {}

        for cacheIndex in terminal(f'ls {baseDir}/{cpu}/cache | grep index -i').split('\n'):
            size = terminal(f'cat {baseDir}/{cpu}/cache/{cacheIndex}/size')
            level = terminal(f'cat {baseDir}/{cpu}/cache/{cacheIndex}/level')
            sharing = terminal(f'cat {baseDir}/{cpu}/cache/{cacheIndex}/shared_cpu_list')

            if cpuCache[cpu].get(level) is not None:
                cpuCache[cpu][level]['amount'] += int(size.replace('K', '').replace('k', ''))

            else:
                cpuCache[cpu][level] = {
                    'amount' : int(size.replace('K', '').replace('k', '')),
                    'shared' : sharing
                }

    return cpuCache

def processorsFromRange(processorRange):
    if '-' in processorRange:
        splittedRange = processorRange.split('-')

        start = int(splittedRange[0])
        end = int(splittedRange[1])

        return list(range(start, end + 1))
    return list(int(element) for element in processorRange.split(','))

def processorSort(processors):
    sorted = [None] * len(processors)

    for processor in processors:
        processorName = list((chr if chr not in string.ascii_letters else '') for chr in processor)

        index = int(''.join(processorName))
        sorted[index] = processor

    return sorted

if __name__ == '__main__':
    args = sys.argv[1:]
    cpu = True

    if not args:
        print('Available governors:')
        for governor in GOVERNORS:
            print('\t' + governor)

        if FREQUENCIES is not None:
            print('\nAvailable scaling frequencies:')
            for frequency in FREQUENCIES:   
                print('\t' + frequency)

        print("\nCurrent status:")
        try:
            freqs = getCurrentScalingFrequencies()
        except:
            pass
        else:
            for index, governor in getCurrentGovernors().items():
                print(f'Processor {index.replace("policy", "")}: \t"{governor}" governor\tfrequency max = {freqs[index]["max"]}, min = {freqs[index]["min"]}')

    elif '-h' in args or '--help' in args:
        print('cputil: cpu util CLI v2.3.0')
        print('usage: cputil [OPTIONS]')
        print('\nOptions:')
        print('    -sg  --set-governor          GOVERNOR     set governor (root)')
        print('    -sfm --set-minimum-frequency FREQUENCY    set minimum frequency (root)')
        print('    -sfM --set-maximum-frequency FREQUENCY    set maximum frequency (root)')
        print('    -cpu CPU       Select which processor to affect with action,')
        print('                   if omitted the action will affect all processors,')
        print('                   to be used with -sg, -sfm, -sfM, -u')
        print('    -i   --info    Show info about CPU')
        print('    -u   --usage   Show CPU usage')
        print('    -avg           If specified, only average usage is shown,')
        print('                   to be used only with -u')

    elif '-i' in args or '--info' in args:
        model = terminal('grep "model name" -i -m 1 /proc/cpuinfo | awk -F \':\'  \'{ print $2 }\'').strip()
        if model:
            print('Model name:\t' + model)

        print('Architecture:\t' + ('amd64 / x86_64 (64 bit)' if sys.maxsize == (2 ** 63 - 1) else 'i386 / i686 (32 bit)'))

        coreCount = terminal('grep "cpu cores" -i -m 1 /proc/cpuinfo | awk -F \':\' \'{ print $2 }\'').strip()
        if coreCount:
            print('Cores count:\t' + coreCount)

        threadCount = terminal('grep processor -c /proc/cpuinfo').strip()
        if threadCount:
            print('Threads count:\t' + threadCount)
        try:
            if 'boost' in os.listdir(DRIVER_DIR):
                if '1' in terminal(f'cat {DRIVER_DIR}/boost'):
                    print('Clock boost:\tactive')
                else:
                    print('Clock boost:\tnot active')
            else:
                print('Clock boost:\tnot available')
        except:
            pass

        try:
            print('Minimum clock:\t' + str(round(int(terminal(f'cat {DRIVER_DIR}/policy0/cpuinfo_min_freq')) / 1000000, 2)) + ' GHz')
        except:
            pass

        try:
            print('Maximum clock:\t' + str(round(int(terminal(f'cat {DRIVER_DIR}/policy0/cpuinfo_max_freq')) / 1000000, 2)) + ' GHz')
        except:
            pass

        try:
            cache = cpuCache()
            threadDistribution = threadDistribution()

        except:
            pass

        else:
            for index, processor in enumerate(processorSort(cache.keys())):
                print(f'\nProcessor {index}:')
                for cacheLevel in cache[processor]:
                    sharing = processorsFromRange(cache[processor][cacheLevel]["shared"])

                    if len(sharing) == int(threadCount):
                        sharing = ['all']

                    else:
                        sharing.remove(index)
                    amount = cache[processor][cacheLevel]["amount"]

                    print(f'    L{cacheLevel} cache: {amount} KB\tshared with processor(s): {", ".join(str(processor) for processor in sharing)}')
                print(f'    Physical core: {threadDistribution[index]}')

    elif '-u' in args or '--usage' in args:
        try:
            usages = cpuUsage()
            averageFrequency, frequencies = cpuFrequency()
        except:
            sys.exit(0)

        if '-cpu' in args:
            cpuIndex = args[args.index('-cpu') + 1]
            usage = usages[int(cpuIndex) + 1]
            frequency = frequencies[int(cpuIndex)]

            print(f'Processor: {cpuIndex}')
            for label, percent in usage.items():
                indent = '\t'

                if len(label) <= 9:
                    indent += '\t'
                print(f'    {label}:{indent}{percent} %')

            print(f'    Frequency:\t\t{frequency} MHz')

        else:
            print('Average:')
            for label, percent in usages[0].items():
                indent = '\t'

                if len(label) <= 9:
                    indent += '\t'

                print(f'    {label}:{indent}{percent} %')
            print(f'    Frequency:\t\t{averageFrequency} MHz')

            if '-avg' not in args:
                for index, thread in enumerate(usages[1:]):
                    print(f'\nProcessor: {index}')

                    for label, percent in thread.items():
                        indent = '\t'

                        if len(label) <= 9:
                            indent += '\t'

                        print(f'    {label}:{indent}{percent} %')
                    print(f'    Frequency: \t\t{frequencies[index]} MHz' )

    elif '-sg' in args or '--set-governor' in args: 
        if os.getuid():
            print('Governor setting requires root privilegies', file=sys.stderr)
            sys.exit(0) 

        try:
            governor = args[args.index('-sg') + 1]

        except:
            governor = args[args.index('--set-governor') + 1]

        if '-cpu' in args:
            cpu = int(args[args.index('-cpu') + 1])

        if not setGovernor(governor, cpu):
            print('Error setting governor')

    elif '-sfm' in args or '--set-min-frequency' in args:
        if os.getuid():
            print('Scaling frequency setting requires root privilegies', file=sys.stderr)
            sys.exit(0) 

        try:
            frequency = args[args.index('-sfm') + 1]
        except:
            frequency = args[args.index('--set-min-frequency') + 1]

        if '-cpu' in args:
            cpu = int(args[args.index('-cpu') + 1])

        if not setMinimumScalingFrequency(frequency, cpu):
            print('Error setting min frequency', file=sys.stderr)
        

    elif '-sfM' in args or '--set-max-frequency' in args:
        if os.getuid():
            print('Scaling frequency setting requires root privilegies', file=sys.stderr)
            sys.exit(0) 

        try:
            frequency = args[args.index('-sfM') + 1]
        except:
            frequency = args[args.index('--set-max-frequency') + 1]

        if '-cpu' in args:
            cpu = int(args[args.index('-cpu') + 1])

        if not setMaximumScalingFrequency(frequency, cpu):
            print('Error setting max frequency', file=sys.stderr)

    else:
        arg = args[0]

        if arg[0] == '-':
            print(f'Error: unrecognised option "{arg}"')

        else:
            print(f'Error: unrecognised argument "{arg}"')
